#pragma once

enum ITEMLIST
{
	//포션류 절대값회복
	NORMAL_HEALTHPOTION		= 301,
	MAGIC_HEALTHHIGHPOTION	= 201,

	//포션류 체력비례회복
	NORMAL_RECOVERYBOOK		= 303,
	MAGIC_RECOVERYBOOK		= 203,
	RARE_RECOVERYBOOK		= 103,
	UNIQUE_RECOVERYBOOK		= 3,	
	
	//무기 류 양손검
	RARE_TWOHANDEDSWORD		= 111,
	UNIQUE_TWOHANDEDSWORD	= 11,

	//무기 류 한손검
	NORMAL_BLADE			= 321,
	MAGIC_BLADE				= 221,	
	RARE_BLADE				= 121,
	UNIQUE_BLADE			= 21,

	//무기 류 활
	NORMAL_ARROW			= 331,
	MAGIC_ARROW				= 231,
	RARE_ARROW				= 131,
	UNIQUE_ARROW			= 31,

	//무기 류 스태프
	NORMAL_STAFF			= 341,
	MAGIC_STAFF				= 241,
	RARE_STAFF				= 141,
	UNIQUE_STAFF			= 41,

	//무기 류 완드
	NORMAL_WAND				= 342,
	MAGIC_WAND				= 242,
	RARE_WAND				= 142,
	UNIQUE_WAND				= 42,

	//무기 류 오브(법사용)
	RARE_OVE				= 143,
	UNIQUE_OVE				= 43,

	//무기 류 낫
	NORMAL_SIDE				= 351,
	MAGIC_SIDE				= 251,
	RARE_SIDE				= 151,
	UNIQUE_SIDE				= 51,

	//방어구 검사 아머
	SWORDMAN_NORMAL_HELMET	= 361,
	SWORDMAN_NORMAL_ARMOR	= 371,
	SWORDMAN_NORMAL_GAUNTLET= 381,
	SWORDMAN_NORMAL_BOOTS	= 391,
	SWORDMAN_MAGIC_HELMET	= 261,
	SWORDMAN_MAGIC_ARMOR	= 271,
	SWORDMAN_MAGIC_GAUNTLET	= 281,
	SWORDMAN_MAGIC_BOOTS	= 291,
	SWORDMAN_RARE_HELMET	= 161,
	SWORDMAN_RARE_ARMOR		= 171,
	SWORDMAN_RARE_GAUNTLET	= 181,
	SWORDMAN_RARE_BOOTS		= 191,
	SWORDMAN_UNIQUE_HELMET	= 61,
	SWORDMAN_UNIQUE_ARMOR	= 71,
	SWORDMAN_UNIQUE_GAUNTLET= 81,
	SWORDMAN_UNIQUE_BOOTS	= 91,
	//방어구 기사 아머
	KNIGHT_NORMAL_HELMET	= 362,
	KNIGHT_NORMAL_ARMOR		= 372,
	KNIGHT_NORMAL_GAUNTLET	= 382,
	KNIGHT_NORMAL_BOOTS		= 392,
	KNIGHT_MAGIC_HELMET		= 262,
	KNIGHT_MAGIC_ARMOR		= 272,
	KNIGHT_MAGIC_GAUNTLET	= 282,
	KNIGHT_MAGIC_BOOTS		= 292,
	KNIGHT_RARE_HELMET		= 162,
	KNIGHT_RARE_ARMOR		= 172,
	KNIGHT_RARE_GAUNTLET	= 182,
	KNIGHT_RARE_BOOTS		= 192,
	KNIGHT_UNIQUE_HELMET	= 62,
	KNIGHT_UNIQUE_ARMOR		= 72,
	KNIGHT_UNIQUE_GAUNTLET	= 82,
	KNIGHT_UNIQUE_BOOTS		= 92,

	//방어구 바바리안 아머
	BABARIAN_RARE_HELMET	= 163,
	BABARIAN_RARE_ARMOR		= 173,
	BABARIAN_RARE_GAUNTLET	= 183,
	BABARIAN_RARE_BOOTS		= 193,
	BABARIAN_UNIQUE_HELMET	= 63,
	BABARIAN_UNIQUE_ARMOR	= 73,
	BABARIAN_UNIQUE_GAUNTLET= 83,
	BABARIAN_UNIQUE_BOOTS	= 93,

	//방어구 법사(여) 아머
	MAGE_NORMAL_HELMET		= 364,
	MAGE_NORMAL_ARMOR		= 374,
	MAGE_NORMAL_GAUNTLET	= 384,
	MAGE_NORMAL_BOOTS		= 394,
	MAGE_MAGIC_HELMET		= 264,
	MAGE_MAGIC_ARMOR		= 274,
	MAGE_MAGIC_GAUNTLET		= 284,
	MAGE_MAGIC_BOOTS		= 294,
	MAGE_RARE_HELMET		= 164,
	MAGE_RARE_ARMOR			= 174,
	MAGE_RARE_GAUNTLET		= 184,
	MAGE_RARE_BOOTS			= 194,
	MAGE_UNIQUE_HELMET		= 64,
	MAGE_UNIQUE_ARMOR		= 74,
	MAGE_UNIQUE_GAUNTLET	= 84,
	MAGE_UNIQUE_BOOTS		= 94,

	//방어구 궁수 아머
	ARCHER_NORMAL_HELMET	= 365,
	ARCHER_NORMAL_ARMOR		= 375,
	ARCHER_NORMAL_GAUNTLET	= 385,
	ARCHER_NORMAL_BOOTS		= 395,
	ARCHER_MAGIC_HELMET		= 265,
	ARCHER_MAGIC_ARMOR		= 275,
	ARCHER_MAGIC_GAUNTLET	= 285,
	ARCHER_MAGIC_BOOTS		= 295,
	ARCHER_RARE_HELMET		= 165,
	ARCHER_RARE_ARMOR		= 175,
	ARCHER_RARE_GAUNTLET	= 185,
	ARCHER_RARE_BOOTS		= 195,
	ARCHER_UNIQUE_HELMET	= 65,
	ARCHER_UNIQUE_ARMOR		= 75,
	ARCHER_UNIQUE_GAUNTLET	= 85,
	ARCHER_UNIQUE_BOOTS		= 95,
	
	//방어구 여검사 아머
	VALKYRIE_RARE_HELMET	= 166,
	VALKYRIE_RARE_ARMOR		= 176,
	VALKYRIE_RARE_GAUNTLET	= 186,
	VALKYRIE_RARE_BOOTS		= 196,
	VALKYRIE_UNIQUE_HELMET	= 66,
	VALKYRIE_UNIQUE_ARMOR	= 76,
	VALKYRIE_UNIQUE_GAUNTLET= 86,
	VALKYRIE_UNIQUE_BOOTS	= 96
};